### ISSUE TITLE
first errors found

### ISSUE THREAD

**Issue by blb4github** [klaashoekstra94/heishamon_rules_minify#1]
I did test, I did see the following errors:

```
&& became & &
|| became | |
!= became ! =
%hour became % hour
```

After fixings this (in text editor) there is still an error but not completely clear, the logging says:
ERROR: Expected a parenthesis block, function, number or variable

**Comment by klaashoekstra94** [comment]
Commit 7f72707 should have fixed the errors for `&&`, `||`, `!=`, and `%hour`. I'm not sure yet about the expected parenthesis block, could you send me the ruleset that generates that error so I can test it?

Edit: I have not published a new release with above fixes, so if you want to test it you have to check out the code :-)

**Comment by blb4github** [comment]
maybe stupid question, but what is the easiest way to update?

**Comment by blb4github** [comment]
I've updated manually the .py file, all above errors are fixed; great! I do get the same error. Attached my current ruleset.

[Heishamon_rules20240210.txt](https://github.com/klaashoekstra94/heishamon_rules_minify/files/14227107/Heishamon_rules20240210.txt)


Update: I have seen some other differences:

it seems negative values change from e.g. -5 to - 5. I don't know if that could cause errors;
it seems some spaces are replaced by another character (but shows like a space).

**Comment by klaashoekstra94** [comment]
I just released an update with some more fixes. Your input seems to be working on v3.2.3 now. On the alpha release of the new rules library the HeishaMon resets most of the time when trying to upload the full ruleset, but sometimes it does upload correctly. I'm not sure yet why that is. But I don't think that has anything to do with the minifier, as the same happens when I use the unminified ruleset as you provided.

**Comment by blb4github** [comment]
Great, I’ll test later as I’m not at home next days. I don’t expect the ruleset to work with @curlymoo latest version, the size it too big.

**Comment by blb4github** [comment]
I've been able to test via VPN with my current ruleset; it works, great!!
