### ISSUE TITLE
option for only removing the comment

### ISSUE THREAD

**Issue by blb4github** [klaashoekstra94/heishamon_rules_minify#3]
Now with the new v5 hardware (based on ESP12) the rules space is much bigger than the 'old' version (based on ESP8266) and it seems rules are also stored much more condensed. It seems not necessary to minimize the rules set but it would be still nice to have the comments. Maybe it would be possible (with e.g. a command line option) to select the 2 functions (removing comment & minimize the rules set)?

**Comment by klaashoekstra94** [comment]
Hey, I made an extra option to only remove comments. Before I merge it, could you test if it works as expected? (#4)

Also, how is the V5 hardware? I've read that the firmware for it is still a little buggy? I now have the S0 measurements, A OneWire sensor and an OpenTherm thermostat connected to it and notice it is getting quite slow and also the temperature measurement fails sometimes. So I hope the new hardware will also be a bit faster besides having more rules storage. But I guess I'll have to wait for the next batch to find out.

**Comment by blb4github** [comment]
Thanks for the version 0.03! I don't see a zip file for this version, how should I install & test? I'm using macbook.

About v5: for me this new version is running fine, the only issue is 2 resistors for the (added) relays do have a wrong value, this can be fixed (see topic on tweakers) but will for sure be fixed by the developer for the new batch.

**Comment by klaashoekstra94** [comment]
I haven't released it yet, the sources are in PR #4. Can you build it yourself from there?

**Comment by klaashoekstra94** [comment]
Have you already had the time to test it? Because if it works for you now then I shall merge the PR and create the new release

**Comment by blb4github** [comment]
Sorry, I was away over the weekend, I'll try tonight.

**Comment by blb4github** [comment]
Hi, I still didn't find the time to figure out how to test is, sorry.

**Comment by klaashoekstra94** [comment]
No worries, we all have busy moments every now and then!

**Comment by blb4github** [comment]
Finally I have tested it. It was a bit complex, first I had to figure out it was not installing anymore on my macbook but I managed to install python on a windows machine and to install the latest version. the -h and -p options work but the -c options gives an error:

```
C:\Programs\HeishaMon>heishamon-rules-minify -h HeishamonRules_20240618.txt HeishamonRulesC20240618.txt
usage: heishamon-rules-minify [-h] [-p] input output

positional arguments:
  input        input rules file
  output       output rules file

options:
  -h, --help   show this help message and exit
  -p, --print  print the output on the commandline

C:\Programs\HeishaMon>heishamon-rules-minify -c HeishamonRules_20240618.txt HeishamonRulesC20240618.txt
usage: heishamon-rules-minify [-h] [-p] input output
heishamon-rules-minify: error: unrecognized arguments: -c
```

**Comment by klaashoekstra94** [comment]
Sorry for the late reply, it seems like you built the version on the main branch, that one does not have the -c option yet. Can you checkout the branch called '3-option-for-only-removing-the-comment' and build that version?

**Comment by blb4github** [comment]
Sorry, I tried all kind of things, spend many hours on it but I'm stuck, no clue how to build that last version.

**Comment by klaashoekstra94** [comment]
No problem, if you can send me your input file I can run it and send the minified version back

**Comment by blb4github** [comment]
Attached my latest rules set which I used with minify.

[Heishamon_rules20240317.txt](https://github.com/user-attachments/files/16058448/Heishamon_rules20240317.txt)

**Comment by klaashoekstra94** [comment]
Sorry for the late response, but thank you for the ruleset. I found another bug in removing only the comments but that should be fixed now. Can you confirm the minified version below is OK? Because in that case I will merge the pull request linked to this issue.

[Heishamon_rules20240317_minified_comments_only.txt](https://github.com/user-attachments/files/16227562/Heishamon_rules20240317_minified_comments_only.txt)

**Comment by blb4github** [comment]
Hi, it works, thanks! In the mean time I'm using some other rules already but I have loaded this version and it runs without errors. It would be great to use it (now with only comment) to document the rules set within the set!

**Comment by klaashoekstra94** [comment]
That's good news! I released a new version v0.0.3 so you can update and use it now.

**Comment by blb4github** [comment]
Hi Klaas, I have successfully used the new version, it works indeed! But I could only use it on windows, not on my mac. Would it be possible to use it (as earlier version) on mac as well?

update: I was trying too complex (compile it myself), I did now just do `pip install heishamon-rules-minify==0.0.3` in the terminal on my mac and the latest version is installed!

**Comment by klaashoekstra94** [comment]
I have no experience with using it on a Mac but I could look into it. Can you make a separate issue for that?

**Comment by blb4github** [comment]
Not needed anymore, it works now, see update in my earlier comment.
